dist: trusty
language: generic
branches:
  only:
  - source
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
  - sudo dpkg -i hugo_0.21_Linux-64bit.deb
script:
  - hugo
deploy:
  on:
    branch: source
  github_token: $GITHUB_TOKEN
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
