baseurl: http://madhead.me/
title: madhead
author: madhead <siarhei.krukau@gmail.com>
theme: BluestNight
enableRobotsTXT: true

params:
  tagline: Never tell me the odds!
  hashover: false
  widgets:
    recent_articles: true
    categories: true
    tags: true
    tags_counter: true
  social:
    github: madhead
    instagram: madhead_
    linkedin: krukaus
    reddit: mad-head
    twitter: madhead_
    steam: siarhei_k

menu:
  main:
    - name: Posts
      weight: 1
      url: "/post"
    - name: CV
      weight: 2
      url: "/cv.html"

outputs:
  home:
  - HTML
  - CSS
  - RSS
  - AMP
  page:
  - HTML
  - AMP
